CarSharing/Controllers/Api/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using CarSharing.Models.Identity;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using static Microsoft.AspNetCore.Hosting.Internal.HostingApplication;

namespace CarSharing.Controllers.Api
{
    [Route("api/user")]
    [ApiController]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class UserController : Controller
    {
        private readonly UserManager<User> userManager;
        public UserController(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }

        [Route("getlogin")]
        [HttpGet]
        public IActionResult getLogin()
        {
            return Ok(User.Identity.Name);
        }

        [HttpGet]
        [Route("getusers")]
        [Authorize(Roles = "admin")]
        public ActionResult<IEnumerable<User>> getUsers(int count = 100, int offset = 0)
        {
            return userManager.Users.Skip(offset).Take(count).ToList();
        }

        [HttpGet]
        [Route("getuser")]
        [Authorize(Roles = "admin")]
        public ActionResult<User> getUser(int id)
        {
            return userManager.Users.FirstOrDefault(x => x.Id == id);
        }
    }
}

CarSharing/Controllers/CallController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarSharing.Models.Database;
using CarSharing.Models.Project;
using Microsoft.AspNetCore.Mvc;

namespace CarSharing.Controllers
{
    public class CallController : Controller
    {
        private ICallRepository repository;
        public CallController(ICallRepository repo)
        {
            repository = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Call call)
        {
            repository.AddCall(call);
            return (PartialView());
        }

        [HttpPost]
        public IActionResult SetServer(Call call)
        {
            var edCall = repository.Calls.FirstOrDefault(x => x.CallID == call.CallID);
            edCall.Served = true;
            repository.UpdateCall(edCall);
          
            return (PartialView());
        }

        [HttpPost]
        public IActionResult Delete(Call call)
        {
            var delCall = repository.Calls.FirstOrDefault(x => x.CallID == call.CallID);
            repository.DeleteCall(delCall);

            return (PartialView());
        }
    }
}

CarSharing/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/style/bundle.min.css" />
    @RenderSection("includeCSS", false)
    <script src="~/javascript/bundle.min.js"></script>
    @RenderSection("IncludeJS", false)

</head>
<body> 
    <style>
        .flex-grow {
            flex: 1 0 auto;
        }
    </style>
    <div class="container-fluid d-flex flex-column h-100">
        <header>          
            <div class="row " style=" background-color:#343a40;">
                @await Html.PartialAsync("_Header")               
            </div>
        </header>
        <div class="row d-flex flex-row  bd-highlight  flex-grow">
            <div class="col-lg-2 col-md-4 shadow">
                @await Html.PartialAsync("_Menu")
            </div>
            <div class="col-lg-10 col-md-8">              
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

CarSharing/Areas/Admin/Views/Shared/_Header.cshtml
<div class="col-lg-2 col-md-4 shadow d-flex pl-5 navbar-expand-lg h-100 p-2" >
    <a href="@Url.Action("Index", "Home")" class="navbar-brand d-flex align-items-center"  style="color:white;">
        <i id="iconcollapse" class="fa fas fa-car fa-sm mr-2" aria-hidden="true"></i>
        <strong>CPanel</strong>
    </a>
</div>
<div class="col-lg-10 col-md-8 d-flex justify-content-end">
    <a href="/" class=" d-flex align-items-center btn" style="color:white;">
        <i id="iconcollapse" class="fa fas fa-arrow-circle-left fa-sm mr-2" aria-hidden="true"></i>
        <strong>Back to site</strong>
    </a>
</div>

CarSharing/Areas/Admin/Views/Shared/_Menu.cshtml
<style>
  .navbar-nav > li > a, .navbar-brand {
     font-weight:300;
}
</style>

<nav class="navbar-light  p-3 pl-4">

    <ul class="navbar-nav flex-column">
        <li class="nav-item">
            <a href="@Url.Action("Index", "Home", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "Index", controllers: "Home", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/home-run.png" style="height:16px; width: 16px;" class="mr-2" />
                <strong>Main page</strong>
            </a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("List", "Call", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "List", controllers: "Call", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/phone.png" style="height:16px; width: 16px;" class="mr-2" />
                <strong>Required call</strong>
            </a>
        </li>
    </ul>
    <hr class="mr-3" />


    <div class="row pt-5">
        <hr style="width: 30%;" />
        <i id="iconcollapse" class="fa fa-car fa-fw pt-2" aria-hidden="true"></i>
        <hr style="width: 30%;" />
    </div>
    <ul class="navbar-nav flex-column">
        <li class="nav-item">
            <a href="@Url.Action("List", "Car", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "List", controllers: "Car", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/list (1).png" style="height:16px; width: 16px;" class="mr-3" />
                <strong>Cars</strong>
            </a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Add", "Car", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "Add", controllers: "Car", areas: "Admin", cssClass: "active")">
                <i id="iconcollapse" class="fa fa-plus fa-fw mr-2" aria-hidden="true"></i>
                <strong>Add car</strong>
            </a>
        </li>
    </ul>

    <div class="row pt-5">
        <hr style="width: 30%;" />
        <i id="iconcollapse" class="fa fa-apple fa-fw pt-2" aria-hidden="true"></i>
        <hr style="width: 30%;" />
    </div>
    <ul class="navbar-nav flex-column">
        <li class="nav-item">
            <a href="@Url.Action("List", "Brand", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "List", controllers: "Brand", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/list (1).png" style="height:16px; width: 16px;" class="mr-3" />
                <strong>Brands</strong>
            </a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Add", "Brand", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "Add", controllers: "Brand", areas: "Admin", cssClass: "active")">
                <i id="iconcollapse" class="fa fa-plus fa-fw mr-2" aria-hidden="true"></i>
                <strong>Add brand</strong>
            </a>
        </li>
    </ul>

    <div class="row pt-5">
        <hr style="width: 30%;" />
        <i id="iconcollapse" class="fa fa-users fa-fw pt-2" aria-hidden="true"></i>
        <hr style="width: 30%;" />
    </div>
    <ul class="navbar-nav flex-column">
        <li class="nav-item">
            <a href="@Url.Action("List", "User", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "List", controllers: "User", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/list (1).png" style="height:16px; width: 16px;" class="mr-3" />
                <strong>Users</strong>
            </a>
        </li>
    </ul>

    <div class="row pt-5">
        <hr style="width: 30%;" />
        <i id="iconcollapse" class="fa fa-share-alt fa-fw pt-2" aria-hidden="true"></i>
        <hr style="width: 30%;" />
    </div>
    <ul class="navbar-nav flex-column">
        <li class="nav-item">
            <a href="@Url.Action("Index", "Roles", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "Index", controllers: "Roles", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/list (1).png" style="height:16px; width: 16px;" class="mr-3" />
                <strong>Roles</strong>
            </a>
        </li>
    </ul>

    <div class="row pt-5">
        <hr style="width: 30%;" />
        <img src="~/images/icons/admin/logistics.png" style="height:16px; width: 16px;"/>
        <hr style="width: 30%;" />
    </div>
    <ul class="navbar-nav flex-column">
        <li class="nav-item">
            <a href="@Url.Action("All", "Order", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "All", controllers: "Order", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/admin/list (1).png" style="height:16px; width: 16px;" class="mr-3" />
                <strong>All orders</strong>
            </a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("WaitCheck", "Order", new { Area = "Admin" })" class="nav-link @Html.IsSelected(actions: "WaitCheck", controllers: "Order", areas: "Admin", cssClass: "active")">
                <img src="~/images/icons/profile/list.png" style="height:16px; width: 16px;" class="mr-3" />
                <strong>Wait check</strong>
            </a>
        </li>
    </ul>
</nav>