CarSharing/Models/Project/Brand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarSharing.Models
{
    public class Brand
    {
        public int BrandID { get; set; }
        public string Name { get; set; }

        public ICollection<Car> Cars { get; set; }
        public Brand()
        {
            Cars = new List<Car>();
        }
    }
}

CarSharing/Areas/Admin/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CarSharing.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CarSharing.Areas.Admin.Controllers
{
    public class BrandController : AdminController
    {
        private IRepository repository;

        public BrandController(IRepository repo)
        {
            repository = repo;
        }

        public IActionResult List()
        {
            return View(repository.Brands.Include(x => x.Cars));
        }
         
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Brand brand, IFormFile file)
        {
            int id = repository.AddBrand(brand);

            if (file != null)
            {
                string path = @"wwwroot/images/brand/" + id + ".png";
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Brand brand = repository.Brands.FirstOrDefault(x => x.BrandID == id);

            if (brand == null)
                return NotFound();
            else
                repository.DeleteBrand(brand);

            string path = @"wwwroot/images/brand/" + id + ".png";
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("List");
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            Brand brand = repository.Brands.FirstOrDefault(x => x.BrandID == id);

            return View(brand);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Brand brand, IFormFile file)
        {
            if (file != null)
            {
                string path = @"wwwroot/images/brand/" + brand.BrandID + ".png";

                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
            }

            repository.UpdateBrand(brand);

            return RedirectToAction("List");
        }
    }
}

CarSharing/Areas/Admin/Views/Brand/Add.cshtml
@{
    ViewData["Title"] = "Add new brand";
}

<selection>

    <div class="container">
        <div class="py-5 text-center">
            <h2>Add new brand</h2>
        </div>

        <div class="row">

            <div class="col-md-12 order-md-1">

                <form asp-action="Add" asp-controller="Brand" asp-area="Admin" method="post" enctype="multipart/form-data">

                    <div class="col-md-12 mb-6 p-0">
                        <label>Brand:</label><br />
                        <input type="text" class="form-control" name="Brand.Name" required />
                    </div>

                    @await Component.InvokeAsync(nameof(FileInput), new FileInputParams() { Accept = "png" })

                    <hr class="mb-4">
                    <button class="btn btn-primary btn-lg btn-block" type="submit">Add</button>
                </form>
            </div>
        </div>
    </div>
</selection>

CarSharing/Areas/Admin/Views/Brand/Edit.cshtml
@model Brand
@{
    ViewData["Title"] = "Edit " + Model.Name;
}

<selection>
    <div class="container">
        <div class="row mt-5">
            <div class="col-sm-12 col-md-8 col-lg-2 text-center">
                <img class="img-fluid mh-100 mb-2" src="~/@Html.GetPhotoBrand(@Model.BrandID)" alt="@Model.Name" />
            </div>

            <div class="col-sm-12 col-md-8 col-lg-10">
                <form asp-action="Edit" asp-controller="Brand" asp-area="Admin" asp-route-id="@Model.BrandID" method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="BrandID" />

                    <div class="row">
                        <div class="col-md-12 mb-6 p-0">
                            <label asp-for="Name" class="control-label">Name</label>
                            <input type="text" asp-for="Name" class="form-control" required />
                        </div>
                        @await Component.InvokeAsync(nameof(FileInput), new FileInputParams() { Accept = "png" })
                    </div>
                    <hr class="mb-4">
                    <div class="row  justify-content-lg-around">
                        <div class="col-5 p-0">
                            <a href="@Url.Action("List", "Brand")" class="btn btn-outline-danger btn-block">Cancel</a>
                        </div>
                        <div class="col-5 p-0">
                            <button class="btn btn-outline-success d-inline btn-block" type="submit">Send</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</selection>

CarSharing/Areas/Admin/Views/Brand/List.cshtml
@model IEnumerable<Brand>

@{
    ViewData["Title"] = "Brands";
}

<section>
    <div class="container-fluid p-0">
        <div class="row">
            <table class="table table-striped text-center ">
                <thead>
                    <tr>

                        <th>Logo</th>
                        <th>Name</th>
                        <th>Cars</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody> 
                    @foreach (var br in @Model)
                    {
                        <tr>
                            <td>
                                <img class="mt-2" style="max-height:25px" src="~/@Html.GetPhotoBrand(br.BrandID)" alt="@br.Name" />
                            </td>
                            <td class="align-middle">
                                @br.Name
                            </td>
                            <td class="align-middle">
                                @br.Cars.Count()
                                
                            </td>
                            <td class="align-middle">
                                <a href="@Url.Action("Edit", "Brand", new { id = br.BrandID })" class="btn btn-outline-success">Edit</a>
                            </td>
                            <td class="align-middle">
                                <form asp-action="Delete" asp-area="Admin" asp-route-id="@br.BrandID" method="post" onsubmit="return confirm('Do you want to remove the brand?');" class="d-inline">
                                    <input type="submit" class="btn  btn-outline-danger" value="Delete" />
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</section>